#!/bin/bash
# Preprocessing Script (Pure SPM - No FSL Dependencies)
# Based on Centiloid Project Guidelines
# Uses SPM12 Standalone (Neurodesk) for all processing

set -e

# Check for Subject ID argument
if [ -z "$1" ]; then
    echo "Usage: $0 <subject_id>"
    echo "Example: $0 02"
    exit 1
fi

subject_id=$1
subject="sub-${subject_id}"

echo "=============================================="
echo "Preprocessing Subject: ${subject} (Pure SPM)"
echo "=============================================="

# Load SPM12 (Confirmed version)
if ! ml spm12/r7771 2>/dev/null; then
    echo "Specific SPM12 module not found, trying default..."
    ml spm12
else
    echo "Loaded SPM12/r7771 module."
fi

# Determine the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

# Define paths
SUBJECT_DIR=~/Desktop/derivatives/data/${subject}
PET_DIR="${SUBJECT_DIR}/pet"
ANAT_DIR="${SUBJECT_DIR}/anat"

# Path to the framing CSV file
FRAMING_CSV="${PROJECT_ROOT}/data/references/framing_info.csv"
frame_info=$(grep "AD${subject_id}," "$FRAMING_CSV")
range=$(echo "$frame_info" | cut -d',' -f3)
start_frame=$(echo "$range" | cut -d'-' -f1)
end_frame=$(echo "$range" | cut -d'-' -f2)

echo "Frame range: ${start_frame} to ${end_frame}"

# Prepare input files
PET_4D="${PET_DIR}/${subject}_pet.nii.gz"
MRI_FILE="${ANAT_DIR}/${subject}_T1w.nii.gz"

# Decompress files for SPM (SPM prefers .nii)
echo "Preparing input files..."
if [ -f "$PET_4D" ]; then
    gunzip -kf "$PET_4D" 2>/dev/null || true
fi
if [ -f "$MRI_FILE" ]; then
    gunzip -kf "$MRI_FILE" 2>/dev/null || true
fi

PET_NII="${PET_DIR}/${subject}_pet.nii"
MRI_NII="${ANAT_DIR}/${subject}_T1w.nii"

# Generate the comprehensive SPM MATLAB script
SPM_SCRIPT="${SUBJECT_DIR}/spm_full_preprocessing.m"

echo "Generating SPM preprocessing script..."

cat > "$SPM_SCRIPT" <<MATLABEOF
% ============================================================================
% SPM12 Full Preprocessing Script (Pure SPM - No FSL)
% Generated by 03_preprocessing.sh
% Subject: ${subject}
% ============================================================================

fprintf('\\n=== SPM Preprocessing for ${subject} ===\\n');

% Initialize SPM
spm('defaults', 'PET');
spm_jobman('initcfg');

% Define paths
pet_4d_file = '${PET_NII}';
mri_file = '${MRI_NII}';
pet_dir = '${PET_DIR}';
anat_dir = '${ANAT_DIR}';

% Frame range (from framing_info.csv)
start_frame = ${start_frame};
end_frame = ${end_frame};

% ============================================================================
% STEP 1: Split 4D PET into 3D frames (Pure SPM replacement for fslsplit)
% ============================================================================
fprintf('Step 1: Splitting 4D PET into frames...\\n');

V4d = spm_vol(pet_4d_file);
n_total_frames = numel(V4d);
fprintf('  Total frames in 4D file: %d\\n', n_total_frames);
fprintf('  Using frames %d to %d\\n', start_frame, end_frame);

% Create frames directory
frames_dir = fullfile(pet_dir, 'frames');
if ~exist(frames_dir, 'dir')
    mkdir(frames_dir);
end

% Extract and write selected frames
frame_files = {};
for i = start_frame:end_frame
    if i > n_total_frames
        error('Frame %d exceeds total frames (%d)', i, n_total_frames);
    end
    
    % Read frame data
    Y = spm_read_vols(V4d(i));
    
    % Create output volume
    Vout = V4d(i);
    Vout.fname = fullfile(frames_dir, sprintf('vol_%04d.nii', i));
    Vout.n = [1 1];  % Reset volume index
    
    % Write frame
    spm_write_vol(Vout, Y);
    frame_files{end+1} = [Vout.fname ',1'];
end

fprintf('  Extracted %d frames\\n', numel(frame_files));

% ============================================================================
% STEP 2: Motion Correction (SPM Realignment)
% ============================================================================
fprintf('Step 2: Motion correction (SPM Realignment)...\\n');

matlabbatch = {};
matlabbatch{1}.spm.spatial.realign.estwrite.data = {frame_files'};
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.sep = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.fwhm = 5;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.rtm = 1;  % Register to mean
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.interp = 2;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.weight = '';
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.which = [0 1];  % Mean only
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.interp = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.mask = 1;
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.prefix = 'r';

spm_jobman('run', matlabbatch);

% Find the mean image
mean_pet = fullfile(frames_dir, sprintf('meanvol_%04d.nii', start_frame));
if ~exist(mean_pet, 'file')
    % Try alternative naming
    mean_files = dir(fullfile(frames_dir, 'mean*.nii'));
    if ~isempty(mean_files)
        mean_pet = fullfile(frames_dir, mean_files(1).name);
    else
        error('Mean realigned image not found!');
    end
end

% Copy mean to standard location
pet_avg = fullfile(pet_dir, '${subject}_pet_avg.nii');
copyfile(mean_pet, pet_avg);
fprintf('  Mean PET saved: %s\\n', pet_avg);

% Clean up frames
rmdir(frames_dir, 's');

% ============================================================================
% STEP 3: Coregister PET to MRI
% ============================================================================
fprintf('Step 3: Coregistering PET to MRI...\\n');

matlabbatch = {};
matlabbatch{1}.spm.spatial.coreg.estimate.ref = {[mri_file ',1']};
matlabbatch{1}.spm.spatial.coreg.estimate.source = {[pet_avg ',1']};
matlabbatch{1}.spm.spatial.coreg.estimate.other = {''};
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];

spm_jobman('run', matlabbatch);
fprintf('  Coregistration complete\\n');

% ============================================================================
% STEP 4: Segment MRI (Unified Segmentation - generates deformation field)
% ============================================================================
fprintf('Step 4: Segmenting MRI (Unified Segmentation)...\\n');

tpm_path = fullfile(spm('Dir'), 'tpm', 'TPM.nii');

matlabbatch = {};
matlabbatch{1}.spm.spatial.preproc.channel.vols = {[mri_file ',1']};
matlabbatch{1}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{1}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{1}.spm.spatial.preproc.channel.write = [0 1];  % Save bias corrected

% Tissue classes
for t = 1:6
    matlabbatch{1}.spm.spatial.preproc.tissue(t).tpm = {sprintf('%s,%d', tpm_path, t)};
    matlabbatch{1}.spm.spatial.preproc.tissue(t).ngaus = [1 1 2 3 4 2];
    matlabbatch{1}.spm.spatial.preproc.tissue(t).ngaus = matlabbatch{1}.spm.spatial.preproc.tissue(t).ngaus(t);
    if t <= 3
        matlabbatch{1}.spm.spatial.preproc.tissue(t).native = [1 0];
    else
        matlabbatch{1}.spm.spatial.preproc.tissue(t).native = [0 0];
    end
    matlabbatch{1}.spm.spatial.preproc.tissue(t).warped = [0 0];
end

matlabbatch{1}.spm.spatial.preproc.warp.mrf = 1;
matlabbatch{1}.spm.spatial.preproc.warp.cleanup = 1;
matlabbatch{1}.spm.spatial.preproc.warp.reg = [0 0.001 0.5 0.05 0.2];
matlabbatch{1}.spm.spatial.preproc.warp.affreg = 'mni';
matlabbatch{1}.spm.spatial.preproc.warp.fwhm = 0;
matlabbatch{1}.spm.spatial.preproc.warp.samp = 3;
matlabbatch{1}.spm.spatial.preproc.warp.write = [0 1];  % Forward deformation only

spm_jobman('run', matlabbatch);

% Find the deformation field
def_field = fullfile(anat_dir, 'y_${subject}_T1w.nii');
if ~exist(def_field, 'file')
    error('Deformation field not found: %s', def_field);
end
fprintf('  Segmentation complete. Deformation field: %s\\n', def_field);

% ============================================================================
% STEP 5: Normalize PET to MNI space
% ============================================================================
fprintf('Step 5: Normalizing PET to MNI space...\\n');

matlabbatch = {};
matlabbatch{1}.spm.spatial.normalise.write.subj.def = {def_field};
matlabbatch{1}.spm.spatial.normalise.write.subj.resample = {[pet_avg ',1']};
matlabbatch{1}.spm.spatial.normalise.write.woptions.bb = [-90 -126 -72; 91 91 109];
matlabbatch{1}.spm.spatial.normalise.write.woptions.vox = [2 2 2];
matlabbatch{1}.spm.spatial.normalise.write.woptions.interp = 4;
matlabbatch{1}.spm.spatial.normalise.write.woptions.prefix = 'w';

spm_jobman('run', matlabbatch);

w_pet = fullfile(pet_dir, 'w${subject}_pet_avg.nii');
fprintf('  Normalized PET: %s\\n', w_pet);

% ============================================================================
% STEP 6: Smooth (8mm FWHM - Centiloid standard for PiB)
% ============================================================================
fprintf('Step 6: Smoothing (8mm FWHM)...\\n');

matlabbatch = {};
matlabbatch{1}.spm.spatial.smooth.data = {[w_pet ',1']};
matlabbatch{1}.spm.spatial.smooth.fwhm = [8 8 8];
matlabbatch{1}.spm.spatial.smooth.dtype = 0;
matlabbatch{1}.spm.spatial.smooth.im = 0;
matlabbatch{1}.spm.spatial.smooth.prefix = 's';

spm_jobman('run', matlabbatch);

sw_pet = fullfile(pet_dir, 'sw${subject}_pet_avg.nii');
fprintf('  Smoothed PET: %s\\n', sw_pet);

% ============================================================================
% STEP 7: Rename output for pipeline compatibility
% ============================================================================
fprintf('Step 7: Finalizing output...\\n');

final_output = fullfile(pet_dir, '${subject}_pet_to_MNI_smoothed.nii.gz');

% Read and gzip the smoothed image
V = spm_vol(sw_pet);
Y = spm_read_vols(V);
V.fname = fullfile(pet_dir, '${subject}_pet_to_MNI_smoothed.nii');
spm_write_vol(V, Y);

% Use system gzip (available on all systems)
system(sprintf('gzip -f "%s"', V.fname));

fprintf('\\n=== Preprocessing Complete ===\\n');
fprintf('Final output: %s\\n', final_output);

% Cleanup intermediate files
delete(fullfile(pet_dir, 'w${subject}_pet_avg.nii'));
delete(fullfile(pet_dir, 'sw${subject}_pet_avg.nii'));
delete(fullfile(pet_dir, '${subject}_pet_avg.nii'));

fprintf('Intermediate files cleaned up.\\n');
exit;
MATLABEOF

# --- Run the SPM script ---
echo "Running SPM preprocessing..."

if command -v spm12 &> /dev/null; then
    # Neurodesk Standalone SPM
    spm12 batch "$SPM_SCRIPT"
elif command -v matlab &> /dev/null; then
    # Standard MATLAB
    matlab -nodisplay -nosplash -nodesktop -r "run('$SPM_SCRIPT');"
else
    echo "ERROR: Neither spm12 nor matlab command found."
    exit 1
fi

# Verify output
FINAL_OUTPUT="${PET_DIR}/${subject}_pet_to_MNI_smoothed.nii.gz"
if [ -f "$FINAL_OUTPUT" ]; then
    echo ""
    echo "=============================================="
    echo "SPM Preprocessing Complete!"
    echo "Output: $FINAL_OUTPUT"
    echo "=============================================="
else
    echo "ERROR: Final output not found: $FINAL_OUTPUT"
    exit 1
fi
