#!/bin/bash
# Preprocessing Script (SPM Based - Standard PiB Method)
# Based on Centiloid Project Guidelines
# Uses SPM12 (Neurodesk standard) to replicate SPM8 "Unified Segmentation" workflow.

set -e

# Check for Subject ID argument
if [ -z "$1" ]; then
    echo "Usage: $0 <subject_id>"
    echo "Example: $0 02"
    exit 1
fi

subject_id=$1
subject="sub-${subject_id}"

echo "Preprocessing Subject: ${subject} (SPM Based)"

# --- Step 1: Frame Averaging (Using FSL tools for efficiency) ---
# SPM doesn't have a simple CLI for this, so we use FSL to prepare the static image.
if ! ml fsl/6.0.7.8 2>/dev/null; then
    ml fsl
fi

# Load SPM12 (Confirmed version)
if ! ml spm12/r7771 2>/dev/null; then
    echo "Specific SPM12 module not found, trying default..."
    ml spm12
else
    echo "Loaded SPM12/r7771 module."
fi

# Determine the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

cd ~/Desktop/derivatives/data/${subject}/pet/

# Path to the CSV file
FRAMING_CSV="${PROJECT_ROOT}/data/references/framing_info.csv"
frame_info=$(grep "AD${subject_id}," "$FRAMING_CSV")
range=$(echo "$frame_info" | cut -d',' -f3)
start_frame=$(echo "$range" | cut -d'-' -f1)
end_frame=$(echo "$range" | cut -d'-' -f2)

start_idx=$((start_frame - 1))
num_frames=$((end_frame - start_frame + 1))

echo "Averaging frames $start_frame to $end_frame..."

# Check total frames in the image
total_frames=$(fslval ${subject}_pet.nii.gz dim4)


required_frames=$((start_idx + num_frames))
if [ "$total_frames" -lt "$required_frames" ]; then
    echo "ERROR: Image has only $total_frames frames, but configuration requires up to frame $end_frame (requiring $required_frames total frames)."
    echo "Current configuration in framing_info.csv might be incorrect for this subject."
    exit 1
fi

fslroi ${subject}_pet.nii.gz ${subject}_pet_crop.nii.gz $start_idx $num_frames
fslmaths ${subject}_pet_crop.nii.gz -Tmean ${subject}_pet_avg.nii.gz
# Reorient for consistency with standard space
fslreorient2std ${subject}_pet_avg.nii.gz ${subject}_pet_avg_reoriented.nii.gz
mv ${subject}_pet_avg_reoriented.nii.gz ${subject}_pet_avg.nii.gz
# Unzip for SPM (SPM often prefers .nii)
gunzip -f ${subject}_pet_avg.nii.gz

# Prepare MRI
# Prepare MRI
cd ~/Desktop/derivatives/data/${subject}/anat/
cp ${subject}_T1w.nii.gz ${subject}_T1w_preproc.nii.gz

# Reorient the copy for consistency
# Yields T1w_preproc.reorient.nii.gz
fslreorient2std ${subject}_T1w_preproc.nii.gz ${subject}_T1w_preproc.reorient.nii.gz

# Rename to final T1w.reoriented.nii.gz
mv ${subject}_T1w_preproc.reorient.nii.gz ${subject}_T1w.reoriented.nii.gz

# Prepare for SPM (requires .nii)
gunzip -f ${subject}_T1w.reoriented.nii.gz

# --- Step 2: Generate SPM Batch Script ---
cd ~/Desktop/derivatives/data/${subject}/

# Define paths
# Define paths
mri_file="$(pwd)/anat/${subject}_T1w.reoriented.nii"
pet_file="$(pwd)/pet/${subject}_pet_avg.nii"
spm_script="spm_preprocessing_job.m"

cat > "$spm_script" <<EOF
% SPM Batch Script for Centiloid Preprocessing
% Generated by 03_preprocessing_spm_based.sh

spm('defaults', 'FMRI');
spm_jobman('initcfg');

% --- Auto-Reorient: Reset Origin to Center of Image ---
% Approximates manual AC-PC alignment by centering the origin
files_to_reorient = {'$mri_file', '$pet_file'};
for i = 1:numel(files_to_reorient)
    fname = files_to_reorient{i};
    v = spm_vol(fname);
    M = v.mat;
    % Calculate geometric center of volume in voxels
    com = (v.dim(1:3)' + 1) / 2;
    % We want this voxel coordinate to be (0,0,0) mm
    % M_new * [com; 1] = [0; 0; 0; 1]
    % [R T] * [com; 1] = 0  =>  R*com + T = 0  =>  T = -R*com
    R = M(1:3, 1:3);
    T_new = -R * com;
    M_new = [R T_new; 0 0 0 1];
    spm_get_space(fname, M_new);
end

matlabbatch = {};

% 1. Coregister: Estimate (Reference: MRI, Source: PET)
matlabbatch{1}.spm.spatial.coreg.estimate.ref = {'$mri_file,1'};
matlabbatch{1}.spm.spatial.coreg.estimate.source = {'$pet_file,1'};
matlabbatch{1}.spm.spatial.coreg.estimate.other = {''};
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];

% 2. Segment (Unified Segmentation)
% This generates the forward deformation field (y_*.nii)
matlabbatch{2}.spm.spatial.preproc.channel.vols = {'$mri_file,1'};
matlabbatch{2}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{2}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{2}.spm.spatial.preproc.channel.write = [0 1]; % Save Bias Corrected
matlabbatch{2}.spm.spatial.preproc.tissue(1).tpm = {fullfile(spm('Dir'),'tpm','TPM.nii,1')};
matlabbatch{2}.spm.spatial.preproc.tissue(1).ngaus = 1;
matlabbatch{2}.spm.spatial.preproc.tissue(1).native = [1 0];
matlabbatch{2}.spm.spatial.preproc.tissue(1).warped = [0 0];
matlabbatch{2}.spm.spatial.preproc.tissue(2).tpm = {fullfile(spm('Dir'),'tpm','TPM.nii,2')};
matlabbatch{2}.spm.spatial.preproc.tissue(2).ngaus = 1;
matlabbatch{2}.spm.spatial.preproc.tissue(2).native = [1 0];
matlabbatch{2}.spm.spatial.preproc.tissue(2).warped = [0 0];
matlabbatch{2}.spm.spatial.preproc.tissue(3).tpm = {fullfile(spm('Dir'),'tpm','TPM.nii,3')};
matlabbatch{2}.spm.spatial.preproc.tissue(3).ngaus = 2;
matlabbatch{2}.spm.spatial.preproc.tissue(3).native = [1 0];
matlabbatch{2}.spm.spatial.preproc.tissue(3).warped = [0 0];
matlabbatch{2}.spm.spatial.preproc.tissue(4).tpm = {fullfile(spm('Dir'),'tpm','TPM.nii,4')};
matlabbatch{2}.spm.spatial.preproc.tissue(4).ngaus = 3;
matlabbatch{2}.spm.spatial.preproc.tissue(4).native = [1 0];
matlabbatch{2}.spm.spatial.preproc.tissue(4).warped = [0 0];
matlabbatch{2}.spm.spatial.preproc.tissue(5).tpm = {fullfile(spm('Dir'),'tpm','TPM.nii,5')};
matlabbatch{2}.spm.spatial.preproc.tissue(5).ngaus = 4;
matlabbatch{2}.spm.spatial.preproc.tissue(5).native = [1 0];
matlabbatch{2}.spm.spatial.preproc.tissue(5).warped = [0 0];
matlabbatch{2}.spm.spatial.preproc.tissue(6).tpm = {fullfile(spm('Dir'),'tpm','TPM.nii,6')};
matlabbatch{2}.spm.spatial.preproc.tissue(6).ngaus = 2;
matlabbatch{2}.spm.spatial.preproc.tissue(6).native = [0 0];
matlabbatch{2}.spm.spatial.preproc.tissue(6).warped = [0 0];
matlabbatch{2}.spm.spatial.preproc.warp.mrf = 1;
matlabbatch{2}.spm.spatial.preproc.warp.cleanup = 1;
matlabbatch{2}.spm.spatial.preproc.warp.reg = [0 0.001 0.5 0.05 0.2];
matlabbatch{2}.spm.spatial.preproc.warp.affreg = 'mni';
matlabbatch{2}.spm.spatial.preproc.warp.fwhm = 0;
matlabbatch{2}.spm.spatial.preproc.warp.samp = 3;
matlabbatch{2}.spm.spatial.preproc.warp.write = [1 1]; % Write Deformation Fields

% 3. Normalise: Write (Apply to PET)
matlabbatch{3}.spm.spatial.normalise.write.subj.def(1) = cfg_dep('Segment: Forward Deformations', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','fordef', '()',{':'}));
matlabbatch{3}.spm.spatial.normalise.write.subj.resample = {'$pet_file,1'};
matlabbatch{3}.spm.spatial.normalise.write.woptions.bb = [-90 -126 -72; 91 91 109];
matlabbatch{3}.spm.spatial.normalise.write.woptions.vox = [2 2 2]; % 2mm isotropic
matlabbatch{3}.spm.spatial.normalise.write.woptions.interp = 4;
matlabbatch{3}.spm.spatial.normalise.write.woptions.prefix = 'w';

% 4. Smooth (8mm FWHM)
matlabbatch{4}.spm.spatial.smooth.data(1) = cfg_dep('Normalise: Write: Resampled Images (Subj 1)', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{1}, '.','files'));
matlabbatch{4}.spm.spatial.smooth.fwhm = [8 8 8];
matlabbatch{4}.spm.spatial.smooth.dtype = 0;
matlabbatch{4}.spm.spatial.smooth.im = 0;
matlabbatch{4}.spm.spatial.smooth.prefix = 's';


EOF

# --- Step 3: Run SPM ---
echo "Running SPM Batch..."
# Try running via standalone SPM or MATLAB
if command -v matlab &> /dev/null; then
    matlab -nodisplay -nosplash -nodesktop -r "run('$spm_script'); exit"
elif command -v spm12 &> /dev/null; then
    # Neurodesk specific command might vary, assuming spm12 script execution
    spm12 batch "$spm_script"
else
    echo "WARNING: Neither MATLAB nor SPM12 command found. The batch script '$spm_script' has been generated but not run."
    echo "Please run it manually in your SPM environment."
fi

# --- Step 4: Final Cleanup ---
# Rename output to match pipeline expectation if successful
if [ -f "pet/sw${subject}_pet_avg.nii" ]; then
    gzip -c "pet/sw${subject}_pet_avg.nii" > "pet/${subject}_pet_to_MNI_smoothed.nii.gz"
    echo "SPM Processing Complete. Output: pet/${subject}_pet_to_MNI_smoothed.nii.gz"
fi

echo "SPM Based Preprocessing Script Finished."
